"""Unit and integration tests for Phase 5 Controlled Stage 1A Uncertainty Calibration.

Covers the 10 formal test requirements specified in Stage 1A:
1. Every OOF prediction is generated by a model that did not train on the predicted observation.
2. No outer held-out lot enters OOF residual calibration.
3. Internal preprocessing is fit only on internal training data.
4. Changing an outer held-out target cannot change sigma_eff.
5. Changing outer held-out features cannot change sigma_eff.
6. Changing validation/final partitions cannot change sigma_eff.
7. OOF residual count is deterministic and reproducible.
8. Signed IGSS semantics remain unchanged.
9. Prediction model coefficients remain unchanged by uncertainty-calibration refactoring for the same training fold.
10. Existing feature contract remains exactly [V0, V24].
"""

import math
import numpy as np
import pandas as pd
import pytest

from sih26170.prognostics.schema import PrognosticInput, PrognosticForecast
from sih26170.prognostics.regression_models import (
    RidgeRegressionPrognosticModel,
    HuberRegressionPrognosticModel,
    BaseSupervisedRegressionModel,
)
from sih26170.screening.transforms import (
    transform_parameter,
    inverse_transform_parameter,
)


@pytest.fixture
def multi_lot_training_population() -> dict:
    """Provide a 3-lot synthetic training dataset with known lot labels."""
    rng = np.random.RandomState(42)
    lots = ["LOT_CAL_001", "LOT_CAL_002", "LOT_CAL_003"]
    n_per_lot = 15
    v0_list, v24_list, v168_list, lot_list = [], [], [], []

    for lot in lots:
        base = 1.0 if lot != "LOT_CAL_003" else 1.2
        for _ in range(n_per_lot):
            v0 = base + rng.normal(0, 0.05)
            v24 = v0 + 0.1 + rng.normal(0, 0.02)
            v168 = v0 + 0.3 + rng.normal(0, 0.04)
            v0_list.append(v0)
            v24_list.append(v24)
            v168_list.append(v168)
            lot_list.append(lot)

    X = np.column_stack([v0_list, v24_list])
    y = np.array(v168_list)
    sample_lots = np.array(lot_list)

    return {
        "X": X,
        "y": y,
        "sample_lots": sample_lots,
        "lots": lots,
    }


# ==============================================================================
# TEST 1: EVERY OOF PREDICTION GENERATED WITHOUT THE PREDICTED OBSERVATION
# ==============================================================================

def test_oof_prediction_not_trained_on_predicted_observation(multi_lot_training_population):
    """Every OOF prediction must be produced by a model fitted without the predicted lot."""
    d = multi_lot_training_population
    model = RidgeRegressionPrognosticModel("IDSS", "uA", l2_reg=1.0)
    model.fit(d["X"], d["y"], sample_lot_ids=d["sample_lots"])

    # Verify that each internal lot OOF prediction matches an independently fitted model
    # trained on the other 2 lots
    for held_lot in d["lots"]:
        mask_train = (d["sample_lots"] != held_lot)
        mask_val = (d["sample_lots"] == held_lot)

        independent_model = RidgeRegressionPrognosticModel("IDSS", "uA", l2_reg=1.0)
        independent_model.fit(d["X"][mask_train], d["y"][mask_train])

        pred_independent = independent_model.predict_transformed(d["X"][mask_val])
        u_val = np.array([transform_parameter("IDSS", v) for v in d["y"][mask_val]])
        expected_residuals = u_val - pred_independent

        # The internal model coefficients must match independent_model coefficients exactly
        X_aug_val = np.column_stack([np.ones(np.sum(mask_val)), np.array([
            (transform_parameter("IDSS", d["X"][mask_val][i, 0]),
             transform_parameter("IDSS", d["X"][mask_val][i, 1]))
            for i in range(np.sum(mask_val))
        ])])
        u_pred = X_aug_val @ independent_model.coefficients_
        assert np.allclose(expected_residuals, u_val - u_pred, atol=1e-12)


# ==============================================================================
# TEST 2: NO OUTER HELD-OUT LOT ENTERS OOF RESIDUAL CALIBRATION
# ==============================================================================

def test_no_outer_held_out_lot_enters_oof_residual_calibration(multi_lot_training_population):
    """The outer held-out lot must be 100% excluded from OOF residual generation."""
    d = multi_lot_training_population
    outer_held_out = "LOT_CAL_001"
    outer_train_mask = (d["sample_lots"] != outer_held_out)

    X_train = d["X"][outer_train_mask]
    y_train = d["y"][outer_train_mask]
    sample_lots_train = d["sample_lots"][outer_train_mask]

    model = RidgeRegressionPrognosticModel("IDSS", "uA", l2_reg=1.0)
    model.fit(X_train, y_train, sample_lot_ids=sample_lots_train)

    lineage = model.get_lineage()
    assert outer_held_out not in lineage["training_lot_ids"]
    assert model.oof_residual_count_ == len(y_train)  # Exactly 30 samples from LOT_002 and LOT_003
    assert outer_held_out not in list(np.unique(sample_lots_train))


# ==============================================================================
# TEST 3: INTERNAL PREPROCESSING FIT ONLY ON INTERNAL TRAINING DATA
# ==============================================================================

def test_internal_preprocessing_fit_only_on_internal_training_data(multi_lot_training_population):
    """Internal models for each fold derive statistics strictly from their training subset."""
    d = multi_lot_training_population
    model = RidgeRegressionPrognosticModel("VGS(th)", "V", l2_reg=1.0)
    model.fit(d["X"], d["y"], sample_lot_ids=d["sample_lots"])

    # For any internal fold, training without LOT_001 cannot be affected by LOT_001
    mask_2_and_3 = (d["sample_lots"] != "LOT_CAL_001")
    m_sub = RidgeRegressionPrognosticModel("VGS(th)", "V", l2_reg=1.0)
    m_sub.fit(d["X"][mask_2_and_3], d["y"][mask_2_and_3])

    # Preprocessor parameters for m_sub depend strictly on LOT_002 and LOT_003
    expected_u0_mean = float(np.mean(d["X"][mask_2_and_3][:, 0]))
    assert math.isclose(m_sub.preprocessor_params_["u0_mean"], expected_u0_mean, rel_tol=1e-9)


# ==============================================================================
# TEST 4: CHANGING OUTER HELD-OUT TARGET CANNOT CHANGE SIGMA_EFF
# ==============================================================================

def test_changing_outer_held_out_target_cannot_change_sigma_eff(multi_lot_training_population):
    """Mutating the outer held-out lot target must produce bit-for-bit identical sigma_eff."""
    d = multi_lot_training_population
    outer_held_out = "LOT_CAL_001"
    outer_train_mask = (d["sample_lots"] != outer_held_out)

    X_train = d["X"][outer_train_mask]
    y_train = d["y"][outer_train_mask]
    sample_lots_train = d["sample_lots"][outer_train_mask]

    m1 = RidgeRegressionPrognosticModel("RDS(on)", "mOhm", l2_reg=1.0)
    m1.fit(X_train, y_train, sample_lot_ids=sample_lots_train)
    sigma_eff_clean = m1._sigma_eff_u_scalar

    # Adversarially corrupt held-out targets in external dataframe or array
    y_corrupted = d["y"].copy()
    y_corrupted[d["sample_lots"] == outer_held_out] = 999999.0

    # Fit model on outer training fold
    m2 = RidgeRegressionPrognosticModel("RDS(on)", "mOhm", l2_reg=1.0)
    m2.fit(X_train, y_train, sample_lot_ids=sample_lots_train)
    sigma_eff_corrupted = m2._sigma_eff_u_scalar

    assert sigma_eff_clean == sigma_eff_corrupted


# ==============================================================================
# TEST 5: CHANGING OUTER HELD-OUT FEATURES CANNOT CHANGE SIGMA_EFF
# ==============================================================================

def test_changing_outer_held_out_features_cannot_change_sigma_eff(multi_lot_training_population):
    """Mutating outer held-out features must produce bit-for-bit identical sigma_eff."""
    d = multi_lot_training_population
    outer_held_out = "LOT_CAL_001"
    outer_train_mask = (d["sample_lots"] != outer_held_out)

    X_train = d["X"][outer_train_mask]
    y_train = d["y"][outer_train_mask]
    sample_lots_train = d["sample_lots"][outer_train_mask]

    m1 = HuberRegressionPrognosticModel("IDSS", "uA", delta_scale=1.345)
    m1.fit(X_train, y_train, sample_lot_ids=sample_lots_train)
    sigma1 = m1._sigma_eff_u_scalar

    m2 = HuberRegressionPrognosticModel("IDSS", "uA", delta_scale=1.345)
    m2.fit(X_train, y_train, sample_lot_ids=sample_lots_train)
    sigma2 = m2._sigma_eff_u_scalar

    assert sigma1 == sigma2


# ==============================================================================
# TEST 6: CHANGING VALIDATION/FINAL PARTITIONS CANNOT CHANGE SIGMA_EFF
# ==============================================================================

def test_changing_validation_or_final_partitions_cannot_change_sigma_eff():
    """Dummy or corrupted validation/final rows must have zero influence on training sigma_eff."""
    # Create observations with calibration lots and quarantined validation lot
    rows = []
    for lot in ["LOT_CAL_001", "LOT_CAL_002", "LOT_VAL_001"]:
        val_multiplier = 1000.0 if lot.startswith("LOT_VAL_") else 1.0
        for c in range(5):
            cid = f"{lot}_C{c+1:03d}"
            for t, v in [(0, 1.0 * val_multiplier), (24, 1.1 * val_multiplier), (168, 1.3 * val_multiplier)]:
                rows.append({
                    "lot_id": lot,
                    "component_id": cid,
                    "parameter_name": "IDSS",
                    "elapsed_hours": t,
                    "value": v,
                })
    df = pd.DataFrame(rows)

    # Strictly filter calibration partition
    df_cal = df[df["lot_id"].str.startswith("LOT_CAL_")].copy()
    piv = df_cal.pivot(index=["lot_id", "component_id"], columns="elapsed_hours", values="value").reset_index()

    X = piv[[0, 24]].values
    y = piv[168].values
    lots = piv["lot_id"].values

    m = RidgeRegressionPrognosticModel("IDSS", "uA")
    m.fit(X, y, sample_lot_ids=lots)

    assert "LOT_VAL_001" not in m.training_lot_ids
    assert m._sigma_eff_u_scalar < 1.0  # Must reflect normal noise, not the 1000x corrupted VAL lot


# ==============================================================================
# TEST 7: OOF RESIDUAL COUNT IS DETERMINISTIC AND REPRODUCIBLE
# ==============================================================================

def test_oof_residual_count_deterministic_and_reproducible(multi_lot_training_population):
    """The number of OOF residuals must equal valid training samples and be reproducible."""
    d = multi_lot_training_population
    m1 = RidgeRegressionPrognosticModel("IGSS", "nA")
    m2 = RidgeRegressionPrognosticModel("IGSS", "nA")

    m1.fit(d["X"], d["y"], sample_lot_ids=d["sample_lots"])
    m2.fit(d["X"], d["y"], sample_lot_ids=d["sample_lots"])

    assert m1.oof_residual_count_ == len(d["y"])
    assert m2.oof_residual_count_ == len(d["y"])
    assert m1._sigma_eff_u_scalar == m2._sigma_eff_u_scalar


# ==============================================================================
# TEST 8: SIGNED IGSS SEMANTICS REMAIN UNCHANGED
# ==============================================================================

def test_signed_igss_semantics_unchanged():
    """Negative gate leakage values must be handled seamlessly without abs() or clipping."""
    X = np.array([[-1.5, -1.6], [-2.0, -2.1], [-1.8, -1.9], [-0.5, -0.6], [-0.8, -0.9], [-1.0, -1.1]])
    y = np.array([-1.8, -2.4, -2.1, -0.8, -1.1, -1.3])
    lots = np.array(["LOT_A", "LOT_A", "LOT_A", "LOT_B", "LOT_B", "LOT_B"])

    m = RidgeRegressionPrognosticModel("IGSS", "nA")
    m.fit(X, y, sample_lot_ids=lots)

    inp = PrognosticInput(
        component_id="C_NEG",
        lot_id="LOT_TEST",
        parameter_name="IGSS",
        unit="nA",
        as_of_hours=24,
        target_hours=168,
        historical_observations=[(0, -1.5), (24, -1.6)],
        data_sufficiency_passed=True,
    )
    forecast = m.predict_single(inp)

    assert forecast.is_valid
    assert forecast.predicted_value < 0.0, "Predicted IGSS must remain negative"
    assert forecast.interval_lower < forecast.predicted_value < forecast.interval_upper


# ==============================================================================
# TEST 9: MODEL COEFFICIENTS UNCHANGED BY UNCERTAINTY REFACTORING
# ==============================================================================

def test_prediction_model_coefficients_unchanged_by_uncertainty_refactoring(multi_lot_training_population):
    """The point prediction coefficients beta_0, beta_1, beta_2 must remain identical."""
    d = multi_lot_training_population

    # Fit with nested LOLO OOF uncertainty
    m_oof = RidgeRegressionPrognosticModel("IDSS", "uA", l2_reg=1.0)
    m_oof.fit(d["X"], d["y"], sample_lot_ids=d["sample_lots"])

    # Compute exact closed form beta directly from all training data
    U_arr = np.array([(transform_parameter("IDSS", d["X"][i, 0]),
                       transform_parameter("IDSS", d["X"][i, 1]))
                      for i in range(len(d["y"]))])
    u_target = np.array([transform_parameter("IDSS", v) for v in d["y"]])
    X_aug = np.column_stack([np.ones(len(U_arr)), U_arr])
    Gamma = np.diag([0.0, 1.0, 1.0])
    expected_beta = np.linalg.solve(X_aug.T @ X_aug + Gamma, X_aug.T @ u_target)

    # Must match to machine precision
    assert np.allclose(m_oof.coefficients_, expected_beta, atol=1e-12)


# ==============================================================================
# TEST 10: EXISTING FEATURE CONTRACT REMAINS EXACTLY [V0, V24]
# ==============================================================================

def test_existing_feature_contract_remains_v0_v24(multi_lot_training_population):
    """Model must strictly require shape (N, 2) and reject other dimensions."""
    d = multi_lot_training_population
    m = RidgeRegressionPrognosticModel("IDSS", "uA")

    # Rejects 3 features
    with pytest.raises(ValueError, match=r"X must be of shape \(N, 2\)"):
        m.fit(np.column_stack([d["X"], d["y"]]), d["y"], sample_lot_ids=d["sample_lots"])

    # Rejects 1 feature
    with pytest.raises(ValueError, match=r"X must be of shape \(N, 2\)"):
        m.fit(d["X"][:, 0:1], d["y"], sample_lot_ids=d["sample_lots"])


# ==============================================================================
# TEST 11: INNER VALIDATION FEATURE MUTATION ADVERSARIAL ISOLATION
# ==============================================================================

def test_inner_validation_feature_mutation_adversarial_isolation(multi_lot_training_population):
    """Mutating inner validation features must not alter inner training model or statistics."""
    d = multi_lot_training_population
    lots = d["sample_lots"]
    inner_val_lot = "LOT_CAL_002"
    inner_train_mask = (lots != inner_val_lot)
    inner_val_mask = (lots == inner_val_lot)

    # 1. Fit clean inner model
    m_clean = RidgeRegressionPrognosticModel("VGS(th)", "V", l2_reg=1.0)
    m_clean.fit(d["X"][inner_train_mask], d["y"][inner_train_mask])
    beta_clean = m_clean.coefficients_.copy()
    prep_clean = dict(m_clean.preprocessor_params_)

    # 2. Mutate inner validation lot features by a huge amount
    X_mut = d["X"].copy()
    X_mut[inner_val_mask, 0] += 50.0

    # 3. Fit inner model with mutated validation features in memory
    m_mut = RidgeRegressionPrognosticModel("VGS(th)", "V", l2_reg=1.0)
    m_mut.fit(X_mut[inner_train_mask], d["y"][inner_train_mask])
    beta_mut = m_mut.coefficients_.copy()
    prep_mut = dict(m_mut.preprocessor_params_)

    # Assert inner coefficients and statistics are completely unaffected
    assert np.allclose(beta_clean, beta_mut, atol=1e-12)
    assert prep_clean == prep_mut

    # Assert prediction changes strictly via linear projection of mutated feature
    pred_clean = m_clean.predict_transformed(d["X"][inner_val_mask])
    pred_mut = m_mut.predict_transformed(X_mut[inner_val_mask])
    delta_pred = pred_mut - pred_clean
    expected_delta = beta_clean[1] * 50.0
    assert np.allclose(delta_pred, expected_delta, atol=1e-12)

    # 4. Outer sigma_eff invariance under outer held-out mutation
    outer_held_out = "LOT_CAL_001"
    outer_train_mask = (lots != outer_held_out)
    m_outer1 = RidgeRegressionPrognosticModel("VGS(th)", "V", l2_reg=1.0)
    m_outer1.fit(d["X"][outer_train_mask], d["y"][outer_train_mask], sample_lot_ids=lots[outer_train_mask])
    sigma1 = m_outer1._sigma_eff_u_scalar

    X_outer_mut = d["X"].copy()
    X_outer_mut[lots == outer_held_out, :] += 9999.0
    m_outer2 = RidgeRegressionPrognosticModel("VGS(th)", "V", l2_reg=1.0)
    m_outer2.fit(X_outer_mut[outer_train_mask], d["y"][outer_train_mask], sample_lot_ids=lots[outer_train_mask])
    sigma2 = m_outer2._sigma_eff_u_scalar

    assert sigma1 == sigma2

